config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'table-of-dates' => 'table_of_dates#index', as: :table_of_dates
  get 'date/:year.:month.:day' => 'date#show', as: :date
end

app/models/geo.rb
require 'maxminddb'
require 'bahai_date'
require 'solareventcalculator'

class Geo
  # This product includes GeoLite2 data created by MaxMind, available from
  # <a href="http://www.maxmind.com">http://www.maxmind.com</a>.
  # http://dev.maxmind.com/geoip/geoip2/geolite2/
  # http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
  MAXMIND_DATA_FILE = '/usr/share/GeoIP/GeoLite2-City.mmdb'

  attr_reader :ip, :latitude, :longitude, :city, :country, :time_zone,
    :current_time, :sunset_time_today, :current_date, :current_gregorian_date_in_bahai_calendar

  def initialize(ip)
    @ip = ip
    lookup_geo
    calculate_times_for_current_geo
  end

  def bahai_date
    BahaiDate::BahaiDate.new(date: @current_gregorian_date_in_bahai_calendar || Date.today)
  end

  private

    def lookup_geo
      db = MaxMindDB.new(MAXMIND_DATA_FILE)
      results = db.lookup(@ip)
      @latitude = results.location.latitude
      @longitude = results.location.longitude
      @city = results.city.name
      @country = results.country.name
      @time_zone = results.location.time_zone
    end

    def calculate_times_for_current_geo
      @current_time = get_current_time_in_time_zone
      @current_date = get_current_date
      @sunset_time_today = get_sunset_time_today
      @current_gregorian_date_in_bahai_calendar = get_current_gregorian_date_in_bahai_calendar
    end

    def get_current_time_in_time_zone
      Time.now.in_time_zone @time_zone
    end

    def get_current_date
      @current_time.to_date
    end

    def get_sunset_time_today
      calculator = SolarEventCalculator.new(@current_date, @latitude, @longitude)
      calculator.compute_official_sunset(@time_zone)
    end

    def get_current_gregorian_date_in_bahai_calendar
      return @current_date unless sunset_passed?
      @current_date + 1.day
    end

    def sunset_passed?
      @current_time > @sunset_time_today
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/date_controller.rb
require 'render_date_to_image'

class DateController < ApplicationController
  before_action :set_date

  def show
    respond_to do |format|
      format.html
      format.jpeg do
        specify_header_and_send_file(RenderDateToImage.new(@date, Rails.root).perform)
      end
    end
  end

  def specify_header_and_send_file(path)
    response.headers['Content-Length'] = File.size(path).to_s
    send_file path, type: 'image/jpeg', disposition: 'inline'
  end

  def set_date
    @date = BahaiDate::BahaiDate.new(year: params[:year],
                                     month: params[:month],
                                     day: params[:day])
  end
end

app/controllers/home_controller.rb
require 'bahai_date'

class HomeController < ApplicationController
  def index
    @geo = Geo.new(request.remote_ip)
    @date = @geo.bahai_date
  end
end

app/controllers/table_of_dates_controller.rb
class TableOfDatesController < ApplicationController
  def index
    @start_year = 172
    @end_year = 306
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def compose_title(title)
    return "Baha'i Date Today" unless title.present?
    "#{title} — Baha'i Date Today"
  end

  def date_as_params(date)
    { year: date.year.bahai_era,
      month: date.month.number,
      day: date.day.number }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/table_of_dates_helper.rb
require 'bahai_date'

module TableOfDatesHelper
  def year_row(year)
    rows = []
    rows << content_tag(:td, "1 Baha #{year}")
    rows << content_tag(:td, gregorian_equivalent_naw_ruz(year))
    rows << content_tag(:td, twin_holy_days(year))
    rows << content_tag(:td, gregorian_equivalent_twin_holy_days(year))
    rows << content_tag(:td, ayyam_i_ha_days(year))
    rows << content_tag(:td, gregorian_equivalent_ayyam_i_ha(year))
    rows.join.html_safe
  end

  def gregorian_equivalent_naw_ruz(year)
    date = BahaiDate::BahaiDate.new(year: year, month: 1, day: 1)
    date.gregorian_date.strftime('%-d %b %Y')
  end

  def twin_holy_days(year)
    month1, day1 = BahaiDate::OccasionFactory.find(:birth_bab, year).split('.')
    date1 = BahaiDate::BahaiDate.new(year: year, month: month1, day: day1)
    month2, day2 = BahaiDate::OccasionFactory.find(:birth_bahaullah, year).split('.')
    date2 = BahaiDate::BahaiDate.new(year: year, month: month2, day: day2)
    if (month1 != month2)
      "#{date1.day.number} #{date1.month.html}, #{date2.day.number} #{date2.month.html}".html_safe
    else
      "#{date1.day.number}, #{date2.day.number} #{date2.month.html}".html_safe
    end
  end

  def gregorian_equivalent_twin_holy_days(year)
    month1, day1 = BahaiDate::OccasionFactory.find(:birth_bab, year).split('.')
    date1 = BahaiDate::BahaiDate.new(year: year, month: month1, day: day1).gregorian_date
    month2, day2 = BahaiDate::OccasionFactory.find(:birth_bahaullah, year).split('.')
    date2 = BahaiDate::BahaiDate.new(year: year, month: month2, day: day2).gregorian_date
    if (date1.month != date2.month)
      date1.strftime('%-d %b') + ', ' + date2.strftime('%-d %b %Y')
    else
      date1.strftime('%-d') + ', ' + date2.strftime('%-d %b %Y')
    end
  end

  def ayyam_i_ha_days_for(year)
    BahaiDate::Logic.leap?(year) ? 5 : 4
  end

  def ayyam_i_ha_days(year)
    "1-#{ayyam_i_ha_days_for(year)}"
  end

  def gregorian_equivalent_ayyam_i_ha(year)
    date1 = BahaiDate::BahaiDate.new(year: year, month: -1, day: 1).gregorian_date
    date2 = BahaiDate::BahaiDate.new(year: year, month: -1, day: ayyam_i_ha_days_for(year)).gregorian_date
    if (date1.month != date2.month)
      date1.strftime('%-d %b') + ', ' + date2.strftime('%-d %b %Y')
    else
      date1.strftime('%-d') + ', ' + date2.strftime('%-d %b %Y')
    end
  end
end

app/views/date/_card.html.erb
<h1><%= image_tag date_path(date_as_params(@date).merge format: 'jpg'), class: 'date-today card' %></h1>

app/views/date/_nav.html.erb
<div class="row">
  <div class="col s2">
    <%= link_to date_path(date_as_params(@date - 1)) do %>
      <i class="material-icons large">chevron_left</i>
    <% end %>
  </div>
  <div class="col s8 center-align flow-text">
    <p><strong>
      <%= link_to date_path(date_as_params(@date)), rel: 'bookmark' do %>
        <%= @date.long_format %><br />
        (<%= @date.gregorian_date.strftime("%A %-d %B %Y") %>)</a>
      <% end %>
    </strong></p>
    <p>The day starts at sunset on <span class="nowrap"><%= (@date.gregorian_date - 1).strftime("%-d %B %Y") %>.</span></p>
  </div>
  <div class="col s2 right-align">
    <%= link_to date_path(date_as_params(@date + 1)) do %>
      <i class="material-icons large">chevron_right</i>
    <% end %>
  </div>
</div>

app/views/date/show.html.erb
<%= content_for :title, @date.short_format %>
<%= content_for :active, 'home' %>

<%= render 'date/card' %>
<%= render 'date/nav' %>

app/views/date/view.html.erb
<%= content_for :active, 'home' %>

<h1><%= image_tag date_path(year: @date.year.bahai_era,
                           month: @date.month.number,
                             day: @date.day.number,
                          format: 'jpg'), class: 'date-today card' %></h1>

<h4 class="center">
  <%= link_to date_path(year: @date.year.bahai_era,
                       month: @date.month.number,
                         day: @date.day.number), rel: 'bookmark' do %>
    <%= @date.long_format %><br />
    (<%= @date.gregorian_date.strftime("%A %-d %B %Y") %>)</a>
  <% end %>
</h4>

<p class="center">The day starts at sunset on <%= (@date.gregorian_date - 1).strftime("%-d %B %Y") %>.</p>

app/views/home/index.html.erb
<%= content_for :active, 'home' %>

<%= render 'date/card' %>
<%= render 'date/nav' %>

<ul>
  <li>Your IP address is: <%= request.remote_ip %></li>
  <li>Latitude: <%= @geo.latitude %></li>
  <li>Longitude: <%= @geo.longitude %></li>
  <li>City: <%= @geo.city %></li>
  <li>Country: <%= @geo.country %></li>
  <li>Time Zone: <%= @geo.time_zone %></li>
  <li>Current server time: <%= Time.now %></li>
  <li>Current time in Time Zone: <%= @geo.current_time %></li>
  <li>Current date in Time Zone: <%= @geo.current_date %></li>
  <li>Sunset today at Latitude and Longitude: <%= @geo.sunset_time_today %></li>
  <li>Current gregorian date in Baha'i Calendar (i.e. next day if sunset has passed): <%= @geo.current_gregorian_date_in_bahai_calendar %></li>
</ul>

app/views/layouts/_header.html.erb
<header>
  <hgroup>
    <h5 class="site-title"><%= link_to 'Bahá’í Date Today', root_url, title: 'Bahá’í Date Today', rel: 'home' %></h5>
  </hgroup>

  <nav>
    <div class="nav-wrapper grey lighten-4">
      <ul id="nav-mobile" class="left">
        <li class="home<%= ' active' if yield(:active) == 'home' %>">
          <%= link_to(root_url, id: 'home') do %>
            <i class="material-icons left grey-text text-darken-2">home</i>Home
          <% end %>
        </li>

        <li class="bahai-calendar<%= ' active' if yield(:active) == 'bahai-calendar' %>">
          <%= link_to(page_url('bahai-calendar'), id: 'bahai-calendar') do %>
            <i class="material-icons left grey-text text-darken-2">info</i>Bahá’í Calendar
          <% end %>
        </li>

        <li class="table-of-dates<%= ' active' if yield(:active) == 'table-of-dates' %>">
          <%= link_to(page_url('table-of-dates'), id: 'table-of-dates') do %>
            <i class="material-icons left grey-text text-darken-2">view_column</i>Table of Dates
          <% end %>
        </li>

        <li class="about<%= ' active' if yield(:active) == 'about' %>">
          <%= link_to(page_url('about'), id: 'about') do %>
            <i class="material-icons left grey-text text-darken-2">help</i>About
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= compose_title(yield(:title)).html_safe %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= google_webfonts_link_tag :material_icons %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<%= content_for :title, 'About' %>
<%= content_for :active, 'about' %>

<h3>About</h3>

<p>The <a href="http://www.bahaidate.today/bahai-calendar/" title="About the Bahá’í Calendar">Bahá’í calendar</a>, also called the Badí‘ calendar (badí‘ means wondrous or unique), was created by the founders of the Bahá’í Faith in the 1800s. In <a href="http://universalhouseofjustice.bahai.org/activities-bahai-community/20140710_001" title="Letter dated 10 July 2014, To the Bahá’ís of the World">a letter dated 10 July 2014</a> the international governing council of the Bahá’í Faith, the Universal House of Justice, called upon the Bahá’ís of the East and West to adopt “<em>the provisions that will unite them in the common implementation of the Badí‘ calendar.</em>”</p>

<p>They conclude their letter:</p>

<blockquote>
  <p>“The adoption of a new calendar in each dispensation is a symbol of the power of Divine Revelation to reshape human perception of material, social, and spiritual reality. Through it, sacred moments are distinguished, humanity’s place in time and space reimagined, and the rhythm of life recast. Next Naw-Rúz will mark yet another historic step in the manifestation of the unity of the people of Bahá and the unfoldment of Bahá’u’lláh’s World Order.”</p>
</blockquote>
<hr>

<p>This site was created to contribute to the common adoption of the calendar. Every day, we release a simple post showing the date today, including:</p>

<ul>
  <li>the day of the week: there are seven days and the week starts on Saturday</li>

  <li>the day of the month: there are nineteen days in each month and each day of the month has its own name. These names happen to be the same as the names of the months of the year.</li>

  <li>the name of the month: there are nineteen months.</li>

  <li>the year: the year is the number of years since the start of the calendar in 1844.</li>
</ul>

<p>The post will also show if there is a Feast or Holy day either today or coming up tomorrow. Bear in mind that the Bahá’í day starts at sunset.</p>

<p>We hope that by checking these posts often, you can gradually memorize the names of the days and months and begin to integrate the calendar into your life. If you like us on Facebook, you’ll receive notifications when there is a post. To receive a notification every day, click “Get Notifications” under the Liked button:</p>

<p><img alt="notifications" class="aligncenter" height="168" src="<%= image_url('notifications.png') %>" width="368"></p>

<p>You can also subscribe to receive an email every time there is a post by entering your email address in the space provided at the top of the site, and clicking Subscribe. You will receive a confirmatory email which you will need to click a link on, to validate your email address, and then you will receive posts daily.</p>
<hr>

<p>Please note that this is an individual initiative and is not affiliated with Bahá’í institutions. Also, we cannot guarantee the accuracy of the content. Please let us know if you notice any errors, or have any suggestions. &nbsp;We hope you find this site helpful. &nbsp;Please feel free to share it with your Bahá’í friends.</p>

<p>To get in touch with us email <strong>contact</strong>&nbsp;at&nbsp;<strong>bahaidate.today</strong> or use the form below:</p>

<div class="row">
  <form action="contact-form" method="post" class="col s12">
    <div class="row">
      <div class="input-field col s12 m6">
        <i class="material-icons prefix">account_circle</i>
        <input id="name" type="text" class="validate">
        <label for="name" data-error="required">Name</label>
      </div>

      <div class="input-field col s12 m6">
        <i class="material-icons prefix">email</i>
        <input id="email" type="email" class="validate">
        <label for="email" data-error="invalid">Email</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <i class="material-icons prefix">comment</i>
        <textarea id="comment" rows="20" class="validate materialize-textarea"></textarea>
        <label for="comment" data-error="required">Comment</label>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <button class="btn waves-effect waves-light" type="submit">Submit</button>
      </div>
    </div>
  </form>
</div>

app/views/pages/bahai-calendar.html.erb
<%= content_for :title, "Baha'i Calendar" %>
<%= content_for :active, 'bahai-calendar' %>

<h3>Bahá’í Calendar</h3>

<p>The Bahá’í calendar, also called the Badí‘ calendar (badí‘ means wondrous or unique), is used by followers of the Bahá’í Faith. More information about it can be found on the Wikipedia page: <a href="http://en.wikipedia.org/wiki/Bah%C3%A1%27%C3%AD_calendar">http://en.wikipedia.org/wiki/Bahá’í_calendar</a></p>

<p>Below is a rendition of the Bahá’í Calendar showing significant dates, as well as matching dates on the Gregorian calendar. The design is based on the image found on <a href="http://www.bahai.org/dir/community/calendar" target="_blank">this page</a>.<br>
<a href="<%= image_url('bahai-calendar.png') %>"><img height="323" src="<%= image_url('bahai-calendar.png') %>" width="3681"></a></p>

<p>Here is the full view: (<a href="<%= asset_url('bahai-calendar.html') %>" target="_blank">new window</a>)<br>
<iframe height="360px" src="<%= asset_url('bahai-calendar.html') %>" width="960px"></iframe></p>

app/views/table_of_dates/index.html.erb
<% content_for :title, 'Table of Dates' %>
<% content_for :active, 'table-of-dates' %>

<h3>Table of Dates</h3>

<p>The following table is generated using this software: <a href="https://github.com/lessan/bahai-date" target="_blank">https://github.com/lessan/bahai-date</a>, which uses algorithms from a book called <em>Astronomical Algorithms</em> that is often used for such calculations on computer systems.</p>

<p>We make no guarantee for the accuracy of this information &#8211; it is simply an attempt at determining these dates using widely available information.</p>

<table id="table-of-dates">
  <thead>
    <tr class="bold_under">
      <th colspan="2">Naw-Rúz</th>
      <th colspan="2">The Birth of the Báb<br />and The Birth of Bahá’u’lláh</th>
      <th colspan="2">Ayyám-i-Há</th>
    </tr>
    <tr class="line_under">
      <th>Bahá’í<br />Dates</th>
      <th>Gregorian<br />Equivalent</th>
      <th>Bahá’í<br />Dates</th>
      <th>Gregorian<br />Equivalent</th>
      <th>Bahá’í<br />Dates</th>
      <th>Gregorian<br />Equivalent</th>
    </tr>
    </thead>
  <% for year in @start_year..@end_year %>
  <tr>
    <%= year_row(year) %>
  </tr>
  <% end %>
</table>